### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by mmikeww** [intelliants/elitius#2]
the readme said to expect a new version Dec 2013... :(

**Comment by RussellSilvey** [comment]
I wonder the same thing. Just found it and was considering using it to open my own affiliate network.

**Comment by hostquota** [comment]
Just tested it out and had to change the scheme.sql file, have written a new one attached.
Simply locate the original in install/sql/ and replace.
It seems to be quite a good script, but has one file missing, but that may be because I have no commissions yet...the script may write the file, we'll see! Other than that it's worth trying out.

**Comment by backtrackbaba** [comment]
So, still dead!?

**Comment by vbezruchkin** [comment]
Hi,

Yes, at the moment we don't work on this project. A bit focused on the new CMS version, so we probably get back to it in 2018. Anyhow, we would recommend to find an alternative solution.

Cheers

**Comment by mittalyashu** [comment]
Any progress now?

**Comment by vbezruchkin** [comment]
Hi,

At the moment we are not working on this project.
Cheers

**Comment by hostquota** [comment]
Thanks, shame though.
